services:
  - type: web
    name: mavik-ml
    env: python
    rootDir: model
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
